# Auto-generated by update.sh from the host's loaded NVIDIA driver
# (`/proc/driver/nvidia/version`). Do not hand-edit; re-run update.sh instead.
{
  version = "580.173.02";
  sha256 = "sha256-jY65AB4FqaimY9PV0wT+tk7yhE7hhczf2VJ4aCD0bhs=";
}
