# Auto-generated by update.sh from the host's loaded NVIDIA driver
# (/proc/driver/nvidia/version). Do not hand-edit; re-run update.sh instead.
{
  version = "610.57.04";
  sha256 = "sha256-suk1xmuDuwDAyFe8jg7g/VLekoa0DJzB7sKafOfrEW0=";
}
