#!/bin/bash
set -e

cd "$(dirname "${BASH_SOURCE[0]}")"

# Re-pin nvidia-driver-pin.nix to whatever NVIDIA driver is currently loaded,
# so targets.genericLinux.gpu (see home.nix) always builds a userspace
# driver matching the host - mismatched versions between the kernel module
# and userspace libs segfault instead of rendering.
nvidia_version=$(grep -oP '[0-9]+\.[0-9]+\.[0-9]+' /proc/driver/nvidia/version 2>/dev/null | head -1 || true)
if [ -n "$nvidia_version" ]; then
    pinned_version=$(sed -n 's/.*version = "\(.*\)".*/\1/p' nvidia-driver-pin.nix)
    if [ "$nvidia_version" != "$pinned_version" ]; then
        echo "NVIDIA driver changed ($pinned_version -> $nvidia_version), re-pinning nvidia-driver-pin.nix"
        url="https://download.nvidia.com/XFree86/Linux-x86_64/${nvidia_version}/NVIDIA-Linux-x86_64-${nvidia_version}.run"
        sha256=$(nix store prefetch-file --json --hash-type sha256 "$url" | jq -r .hash)
        cat > nvidia-driver-pin.nix <<EOF
# Auto-generated by update.sh from the host's loaded NVIDIA driver
# (/proc/driver/nvidia/version). Do not hand-edit; re-run update.sh instead.
{
  version = "${nvidia_version}";
  sha256 = "${sha256}";
}
EOF
    fi
    git add nvidia-driver-pin.nix
else
    echo "No NVIDIA driver loaded, skipping nvidia-driver-pin.nix update."
fi

# Sync /run/opengl-driver before activating: home-manager's activation warns
# about a missing/stale link, and running the setup first means it never has
# anything to warn about. The setup script installs an /etc/tmpfiles.d entry
# (gcrooted) that recreates the symlink at boot, so root is only needed when
# the store paths actually change - hence the readlink guards, which keep this
# from prompting for sudo on every run.
if [ -n "$nvidia_version" ]; then
    gpu_drivers=$(nix build '.#homeConfigurations.ben.config.targets.genericLinux.gpu.drivers' --no-link --print-out-paths)
    gpu_setup=$(nix build '.#homeConfigurations.ben.config.targets.genericLinux.gpu.setupPackage' --no-link --print-out-paths)
    if [ "$(readlink /run/opengl-driver || true)" != "$gpu_drivers" ] \
        || [ "$(readlink /etc/tmpfiles.d/non-nixos-gpu.conf || true)" != "${gpu_setup}/lib/tmpfiles.d/non-nixos-gpu.conf" ]; then
        echo "Syncing /run/opengl-driver to the pinned NVIDIA userspace libs..."
        sudo "${gpu_setup}/bin/non-nixos-gpu-setup"
    fi
fi

# nix build '.#homeConfigurations.ben.activationPackage' --override-input nix-hm ../nix-hm
nix build '.#homeConfigurations.ben.activationPackage'
./result/activate

# Define source and target folder pairs
declare -A folder_pairs=(
    [${HOME}/.nix-profile/share/applications]="${HOME}/.local/share/applications"
    [${HOME}/.nix-profile/share/icons]="${HOME}/.local/share/icons"
    # Add more pairs as needed
)

echo "${folder_pairs}"
# Loop through folder pairs
for source_folder in "${!folder_pairs[@]}"; do
echo "$source_folder"
    target_folder="${folder_pairs[${source_folder}]}"
    
    # Check if source folder exists
    if [ ! -d "$source_folder" ]; then
        echo "Source folder '$source_folder' does not exist."
        continue
    fi
    
    # Check if target folder exists, if not, create it
    if [ ! -d "$target_folder" ]; then
        mkdir -p "$target_folder"
    fi
    
    # Loop through files in the source folder
    for file in "$source_folder"/*; do
        # Extract the filename from the full path
        filename=$(basename "$file")
        
        # Check if a symlink with the same filename already exists in the target folder
        if [ ! -e "$target_folder/$filename" ]; then
            # Create a symlink in the target folder
            ln -s "$file" "$target_folder/$filename"
            echo "Created symlink for '$filename' in '$target_folder'."
        else
            echo "Symlink for '$filename' already exists in '$target_folder'. deleting and remaking."
            rm "$target_folder/$filename"
            ln -s "$file" "$target_folder/$filename"
        fi
    done
    
    echo "Symlink creation process for '$source_folder' completed."
done
